# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.AddField(
            model_name='item',
            name='excludes',
            field=models.TextField(blank=True, help_text='Separate ech item by comma', null=True),
        ),
    ]
